/* Plunge Picks — centralized product dataset.
   Honest data policy: only categorical fields we can defend are populated.
   Any numeric spec we cannot currently verify is left null with verify:true
   and a note. Do NOT invent specs here. Update verifiedDate when checked. */
window.PLUNGE_PRODUCTS = [
  {
    slug: "the-cold-plunge",
    name: "The Cold Plunge",
    brand: "Plunge",
    merchant: "Plunge",
    affiliateUrl: "https://plunge.com",
    priceCategory: "Premium",
    coolingType: "chiller",         // ice | chiller | both
    chillerIncluded: true,
    chillerCompatible: true,
    minTempF: 39,                   // manufacturer-published
    heating: false,
    portable: false,
    indoor: true,
    outdoor: true,
    upgradeable: false,
    bestFor: "A hands-off automated daily plunge",
    limitation: "High up-front cost; multi-week lead times",
    verifiedDate: "2026-07",
    verify: false,
    notes: "Dimensions/weight need verification against current product page."
  },
  {
    slug: "sun-home-cold-plunge-pro",
    name: "Sun Home Cold Plunge Pro",
    brand: "Sun Home",
    merchant: "Sun Home",
    affiliateUrl: "https://sunhomesaunas.com",
    priceCategory: "Premium",
    coolingType: "chiller",
    chillerIncluded: true,
    chillerCompatible: true,
    minTempF: 32,
    heating: true,
    portable: false,
    indoor: true,
    outdoor: true,
    upgradeable: false,
    bestFor: "The coldest, most integrated premium setup",
    limitation: "Top-of-market price; heavy (~345 lbs), hard to relocate",
    verifiedDate: "2026-07",
    verify: false,
    notes: "Heating availability varies by model — verify configuration."
  },
  {
    slug: "hydragun-supertub",
    name: "Hydragun Supertub",
    brand: "Hydragun",
    merchant: "Hydragun",
    affiliateUrl: "https://hydragun.com",
    priceCategory: "Mid-range",
    coolingType: "chiller",
    chillerIncluded: true,
    chillerCompatible: true,
    minTempF: null,
    heating: false,
    portable: false,
    indoor: true,
    outdoor: true,
    upgradeable: false,
    bestFor: "A real chiller tub at a mid-range price",
    limitation: "Chiller runs on the loud side",
    verifiedDate: "2026-07",
    verify: true,
    notes: "Minimum temperature, dimensions, warranty need verification."
  },
  {
    slug: "polar-monkeys-brainpod-2",
    name: "Polar Monkeys Brainpod 2.0",
    brand: "Polar Monkeys",
    merchant: "Polar Monkeys",
    affiliateUrl: "https://polarmonkeys.com",
    priceCategory: "Mid-range",
    coolingType: "chiller",
    chillerIncluded: true,
    chillerCompatible: true,
    minTempF: null,
    heating: true,
    portable: false,
    indoor: true,
    outdoor: false,
    upgradeable: false,
    bestFor: "Compact spaces and apartments",
    limitation: "Small basin may feel snug for taller users",
    verifiedDate: "2026-07",
    verify: true,
    notes: "Capacity ~55 gal and ~110 lbs empty cited by reviewers — verify. Heating is model-dependent."
  },
  {
    slug: "nordic-wave-viking",
    name: "Nordic Wave Viking Tub",
    brand: "Nordic Wave",
    merchant: "Nordic Wave",
    affiliateUrl: "https://thenordicwave.com",
    priceCategory: "Mid-range",
    coolingType: "both",
    chillerIncluded: false,
    chillerCompatible: true,
    minTempF: null,
    heating: false,
    portable: false,
    indoor: true,
    outdoor: true,
    upgradeable: true,
    bestFor: "An upright, seated plunge with a small floor footprint",
    limitation: "Less internal space; pricing varies by configuration",
    verifiedDate: "2026-07",
    verify: true,
    notes: "Dimensions and chiller options need verification."
  },
  {
    slug: "the-cold-pod",
    name: "The Cold Pod",
    brand: "The Cold Pod",
    merchant: "Amazon",
    affiliateUrl: "https://www.amazon.com/s?k=cold+pod+ice+bath+tub&tag=plungepicks-20",
    priceCategory: "Budget",
    coolingType: "ice",
    chillerIncluded: false,
    chillerCompatible: false,
    minTempF: null,
    heating: false,
    portable: true,
    indoor: true,
    outdoor: true,
    upgradeable: false,
    bestFor: "Testing the cold-plunge habit cheaply before investing",
    limitation: "No temperature control; you supply the ice",
    verifiedDate: "2026-07",
    verify: true,
    notes: "Replace Amazon search link with a specific Special Link once a current product is chosen."
  },
  {
    slug: "stock-tank-diy",
    name: "Galvanized Stock Tank (DIY)",
    brand: "Various",
    merchant: "Amazon",
    affiliateUrl: "https://www.amazon.com/s?k=stock+tank+ice+bath&tag=plungepicks-20",
    priceCategory: "Budget",
    coolingType: "ice",
    chillerIncluded: false,
    chillerCompatible: true,
    minTempF: null,
    heating: false,
    portable: false,
    indoor: false,
    outdoor: true,
    upgradeable: true,
    bestFor: "The lowest possible cost, outdoor DIY setup",
    limitation: "No insulation — burns through ice; industrial look",
    verifiedDate: "2026-07",
    verify: true,
    notes: "Generic category; link to a specific tank product when selected."
  }
];
